config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # auth stuff
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login_submit"
  get "signup" => "users#new", :as => "signup"
  resources :users

  #post stuff
  resources :posts do
     resources :comments
  end
end

app/models/user.rb
class User < ActiveRecord::Base
   self.per_page = 10

   has_many :articles, :dependent => :delete_all
   has_many :posts, :dependent => :delete_all
   has_many :comments, :dependent => :delete_all

   attr_accessor :password
   before_save :encrypt_password
   after_initialize :init
   
   validates_confirmation_of :password
   validates_presence_of :password, :on => :create
   validates_presence_of :email
   validates_uniqueness_of :email

   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

   def init
      # Default our users to the standard role
      self.role ||= 1
   end

   def self.authenticate(email, password)
      user = find_by_email(email)
      #if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      if user && BCrypt::Password.new(user.password_hash) == password
         user
      else
         nil
      end
   end

   def is_admin
      # Role 2 == admin, Role 1 == user
      return Integer(self.role) == 2
   end

   # Promote a user to admin
   def make_admin
      self.role = 2
   end

   def encrypt_password
      if password.present?
         self.password_hash = BCrypt::Password.create(password)
         #self.password_salt = BCrypt::Engine.generate_salt
         #self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   helper_method :can_edit

  # The responder for viewing the signup form
  def new
     @user = User.new
  end

  # The responder for submitting the signup form.
  def create
     @user = User.new(user_params)
     if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, :notice => "Sign up successful!"
     else
        render "new"
     end
  end

  # a user's profile page
  def show
     @user = User.includes(:posts).find(params[:id])
  end

  # the edit page
  def edit
     self_edit_only
     @user = User.find(params[:id])
  end

  # update a user object
  def update
     self_edit_only
     @user = User.find(params[:id])
     if @user.update(update_params)
        redirect_to user_url, :notice => "Update successful!"
     else
        render "edit"
     end
  end

  # Delete a user
  def destroy
     self_edit_only
     @user = User.find(params[:id])
     if @user.destroy
        redirect_to root_path, :notice => "Account deleted!"
     else
        render "edit", :notice => "Deletion failure!"
     end
  end

  # A listing of all users?
  def index
     @users = User.page(params[:page]).order("created_at DESC").all
  end

  private

  def user_params
     params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end

  def update_params
     params.require(:user).permit(:email, :username, :avatar, :bio)
  end

  # Only the same user and admins can edit a user's profile
  def self_edit_only
     #if current_user.id != Integer(params[:id]) && !current_user.is_admin
     if !can_edit
        redirect_to user_url, :notice => "You don't have permission to do that."
     else
     end
  end

  # A view helper, returns true if the user should be able to edit.
  def can_edit
     return current_user && (current_user.id == Integer(params[:id]) || current_user.is_admin)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
<%= form_for @user, :html => { :multipart => true } do |f| %>
   <% if @user.errors.any? %>
      <div class="errors">
         <ul>
            <% for message in @user.errors.full_messages %>
               <li><%= message %></li>
            <% end %>
         </ul>
      </div>
   <% end %>

   <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
   </p>
   <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
   </p>
   <p>
    <%= f.label :bio %>
    <%= f.text_field :bio %>
   </p>
   <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %><br>
    <span><%= image_tag @user.avatar.url(:thumb) %></span>
   </p>
   <%= f.submit "Save", :class => "btn btn-success" %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
   <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
   </p>
   <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
   </p>
   <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
   </p>
   <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
   </p>
   <p class="button"><%= f.submit "Sign up!", :class => "btn btn-success" %></p>
<% end %>

app/views/users/_user.html.erb
<div id="user-<%= user.username %>" class="row">
   <div class="col-md-6">
      <%= link_to (image_tag user.avatar, :width => "100%"), user_path(user) %>
   </div>
   <div class="col-md-6">
      <div class="page-header">
         <h4><%= link_to user.username, user_path(user) %></h4>
      </div>
      <p><%= user.bio %></p>
   </div>
</div>

app/views/users/_user_header.html.erb
<div id="user-header-carousel" class="carousel slide" data-ride="carousel">
   <div class="carousel-inner">
      <div class="item active" style="max-height: 400px; overflow: hidden;">
         <%= image_tag user.avatar.url, :width => "100%", :class => "img img-rounded"  %>
         <div class="carousel-caption">
            <%= image_tag user.avatar.url(:thumb), :class => "img img-rounded" %>
            <h1><%= user.username %></h1>
            <p><%= user.bio %>
            <%= link_to content_tag(:span, "", class:"glyphicon glyphicon-pencil"), edit_user_path(user) if can_edit %>
            </p>
         </div>
      </div>
   </div>
</div>

app/views/users/edit.html.erb
<h2>Editing <%= @user.username %></h2>

<%= render 'user_header', :user => @user %>
<br>
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Edit User Profile</h3>
   </div>
   <div class="panel-body">
      <%= render 'edit_form' %>
   </div>
</div>
<div class="panel panel-default">
   <div class="panel-heading">
      <h4 class="panel-title">
         Dangerous Actions
      </h4>
   </div>
   <div class="panel-body">
      <%= link_to 'Delete', user_path(@user), method: :delete, data: {confirm: 'Are you sure? This will delete all data associated with this account and cannot be undone.'}, :class => "btn btn-danger"  %>
   </div>
</div>

app/views/users/index.html.erb
<h1>User Index</h1>

<%= render(@users) %>

<%= will_paginate @users %>

app/views/users/new.html.erb
<div class="page-header">
   <h1>Join us! <small>We'd love to have you.</small></h1>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'user_header', :user => @user %>

<%= link_to "New Post", new_post_url if can_edit %></br>

<%= render(@user.posts) or "No Posts" %>