config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # auth stuff
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login_submit"
  get "signup" => "users#new", :as => "signup"
  resources :users

  #post stuff
  resources :posts do
     resources :comments
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
   self.per_page = 10


   belongs_to :user
   has_many :comments, :dependent => :delete_all

   has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

   validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

   validates :image, presence: true
   validates :body, presence: true
   validates_presence_of :user

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   helper_method :can_edit

   def index
      @posts = Post.page(params[:page]).order("created_at DESC").includes(:comments).all
   end

   def create
      require_login
      @post = Post.new(post_params)
      @post.user = current_user
      if @post.save
         redirect_to post_url(@post), :notice => "Saved!"
      else
         render "new"
      end
   end
   
   def new
      require_login
      @post = Post.new
   end

   def edit
      @post = Post.find(params[:id])
      self_edit_only(@post)
   end

   def show
      @post = Post.find(params[:id])
   end

   def update
      @post = Post.find(params[:id])
      self_edit_only(@post)
      if @post.update(post_params)
         redirect_to post_url, :notice => "Saved!"
      else
         render "edit"
      end
   end

   def destroy
      @post = Post.find(params[:id])
      self_edit_only(@post)
      @post.destroy
      redirect_to posts_url, :notice => "Post deleted!"
   end

   private

   def post_params
      params.require(:post).permit(:body, :image)
   end

   def self_edit_only (post)
      if !can_edit(post)
         redirect_to post_url, :notice => "You don't have permission to edit this."
      else
      end
   end

   # A helper
   def can_edit (post)
      return true if current_user && (post.user.id == current_user.id || current_user.is_admin)
      return false
   end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_edit_form.html.erb
<div id="post-<%= @post.id %>" class="row">
   <div class="col-md-6">
      <%= image_tag @post.image, :width => "100%", :class => "img-rounded" %>
   </div>
   <div class="col-md-6">
      <div class="page-header">
         <h4>
            <%= @post.created_at.to_formatted_s(:long_ordinal) %>
         </h4>
      </div>
      <%= form_for @post, :html => { :multipart => true } do |f| %>
         <p>
          <%= f.label :body %><br>
          <%= f.text_area :body %>
         </p>
         <%= f.submit "Save", :class => "btn btn-success" %>
      <% end %>
   </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true } do |f| %>
   <p id="file_fields">
    <%= f.label :image %><br>
    <%= f.file_field :image, :id => "file_input" %>
   </p>
   <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, :placeholder => "Like omg #SELFIE!" %>
   </p>
   <%= f.submit "Post!", :class => "btn btn-success" %>
<% end %>

app/views/posts/_post.html.erb
<div id="post-<%= post.id %>" class="row">
   <div class="col-md-6">
      <%= link_to (image_tag post.image, :width => "100%", :class => "img-rounded"), post_path(post) %>
   </div>
   <div class="col-md-6">
      <div class="page-header">
         <h4>
            <%= post.created_at.to_formatted_s(:long_ordinal)  %> by <%= link_to post.user.username, user_path(post.user) %>
            <small><%= link_to (pluralize(post.comments.count, "comment")), post_path(post) %></small>
         </h4>
      </div>
      <p><%= post.body %></p>
   </div>
</div>

app/views/posts/_post_header.html.erb
<div id="user-header-carousel" class="carousel slide" data-ride="carousel">
   <div class="carousel-inner">
      <div class="item active" style="max-height: 200px; overflow: hidden;">
         <%= image_tag @post.user.avatar.url, :width => "100%", :class => "img-rounded"  %>
         <div class="carousel-caption">
            <h1><%= link_to @post.user.username, user_url(@post.user) %></h1>
            <p><%= @post.user.bio %></p>
         </div>
      </div>
   </div>
</div>

app/views/posts/edit.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Edit Post</h3>
   </div>
   <div class="panel-body">
      <%= render 'edit_form' %>
   </div>
</div>
<div class="panel panel-default">
   <div class="panel-heading">
      <h4 class="panel-title">
         Dangerous Actions
      </h4>
   </div>
   <div class="panel-body">
      <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-danger"  %>
   </div>
</div>

app/views/posts/index.html.erb
<div class="page-header">
   <h1>Public Feed</h1>
</div>

<%= link_to "New Post", new_post_url if current_user %>

<%= render(@posts) %>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">Create New Post</h3>
   </div>
   <div class="panel-body">
      <div id="my_camera" style="width:640px; height:480px;"></div>
      <div id="my_result" style="width:640px; height:480px; display:none;"></div>
      <div id="snap" class="btn btn-primary">Snap!</div>
      <div id="cancel" class="btn btn-danger">Retake</div>
      <%= render 'form' %>
   </div>
</div>

app/views/posts/show.html.erb
<%= render 'post_header', :post => @post %>
<%= render(@post) %>
<%= link_to "Edit", edit_post_path(@post) if can_edit @post %><br>

<div class="panel panel-default">
   <div class="panel-heading">
      <h3 class="panel-title">
         <%= pluralize(@post.comments.count, "Comment") %>
      </h3>
   </div>
   <div class="panel-body">
      <%= render(@post.comments) %>
   </div>
</div>

<%= render 'comments/form' if current_user %>