config/routes.rb
Rails.application.routes.draw do
  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # auth stuff
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create", :as => "login_submit"
  get "signup" => "users#new", :as => "signup"
  resources :users

  #post stuff
  resources :posts do
     resources :comments
  end
end

app/views/layouts/_flash.html.erb
<% if flash.count != 0 %>
<div class="flash-messages">
   <% flash.each do |name, msg| %>
      <% @class = (name == 'alert') ? "danger" : "success" %>
         <div class="alert alert-<%= @class %> alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert">
               <span aria-hidden="true">&times;</span>
               <span class="sr-only">Close</span>
            </button>
            <strong><%= name %></strong>
            <%= msg %>
         </div>
   <% end %>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
   <div class="container-fluid">
      <div class="navbar-header">
         <%= link_to 'Selfer', root_path, :class => "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to content_tag(:span, "", class:'glyphicon glyphicon-camera'), new_post_url %></li>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user ? current_user.username : "Menu"  %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
               <li><%= link_to 'Home', root_path %></li>
               <li><%= link_to 'Public Feed', posts_path %></li>
               <li><%= link_to 'Users', users_path %></li>
               <% if current_user %>
                  <li><%= link_to 'My Profile', user_path(current_user) %></li>
                  <li><%= link_to 'Log Out', logout_path %></li>
                  <% if current_user.is_admin %>
                     <li><%= link_to 'Admin', root_path %></li>
                  <% end %>
               <% else %>
                  <li><%= link_to 'Sign In', login_path %></li>
                  <li><%= link_to 'Sign Up', signup_path %></li>
               <% end %>
            </ul>
         </li>
      </ul>

   </div>
</nav>

app/views/layouts/_user_info.html.erb
<div class="user-info">
   <% if current_user %>
      <span><%= current_user.email %> | <%= link_to "Log Out", logout_path %>
         <% if current_user.is_admin %> | ADMIN <% end %>
      </span>
   <% else %>
      <span><%= link_to "Sign Up", signup_path %> | <%= link_to "Log In", login_path %></span>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= @title or "Selfer" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
   <div class="container">
      <br>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/flash' %>

      <%= yield %>
   </div>

</body>
</html>